name: biobb_wf_godmd
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.9
  - biobb_io==4.1.0
  - biobb_structure_utils==4.1.0
  - biobb_analysis==4.1.0
  - biobb_godmd==4.1.0
  - emboss
  - jupyter
  - plotly
  - nglview
  - simpletraj
